browser:
  mysql:
    user: root
    password: 12345678
    ip: localhost
    port: 3306
    database: ft
  node:
    rpcHost: http://192.168.1.148:3090
  log:
    level: info #error info debug
    file:
      enable: false
      path: browser-service.log
      rotationTime: 1 #time.Duration 1:day 2:hour
      maxAge: 15 #day
    console: true
    syncBlockShowNumber: 1000
  tasks:
    - block
    - txs
    - action
    - internalAction
    - feeAction
    - account
    - accountBalance
    - token
    - accountHistory
    - tokenHistory
    - feeHistory
  blockDataChanBufferSize: 10000







